Database.langs = {
    en: {
            "INSTRUCT1": "This is Karl. He is a wood cutter and also our hero.\n\nPress <space> to make this message go away.",
            "INSTRUCT2": "To move, use your arrow keys. Alternatively, \nyou can click or tap a place to make Karl move to it.",
            "INSTRUCT3": "Press <space> to talk with people. You can also\ndo this to read signs, such as the one below\n the tree to the far right.",
            "KARL_SIGN": "Welcome to Karl's house!\nEast: Crossroads.", 
            "CROSS_SIGN1": "Forest Crossroads. Hunting trees is prohibited by\nthe decree of Good King Albert.\nHunt animals instead.",
            "CROSS_SIGN2": "West: Karl's cottage.\nNorth: Port Knox.\nSouth: You don't need to know.\nEast: Wizard's palace.",
            "CROSS_ENTRY1": "Winter is coming and I need a new armchair\nby the fire. One of the soft ones.\nMy back is killing me...",
            "CROSS_ENTRY2": "Maybe that hunter over there would know\nwhere to find one!",
            "KARL_HUNTER_1": "KARL: Hello fair citizen! How goes thy day?",
            "KARL_HUNTER_2": "HUNTER: My day's awesome. Shot two gazelles\n and I'm gonna get a good price for them!\n And who is ye?",
            "KARL_HUNTER_3": "KARL: I'm a jack o' the lumber. I need a new \n armchair but I'm old and my back's not what \nit used to be. I hope someone will chop down \na tree for me to make it.",
            "KARL_HUNTER_4": "HUNTER: Thou art nuts! Haven't you heard?",
            "KARL_HUNTER_5": "KARL: Heard what?",
            "KARL_HUNTER_6": "HUNTER: Cutting down trees is illegal!\n Our fat king axed the trees in this entire\n kingdom to make ships for the navy. The only \ntrees that are left are here in this area,\nso these must not be cut.",
            "KARL_HUNTER_7": "KARL: What! I'm a woodcutter!\nHow will I make a living now?",
            "KARL_HUNTER_8": "HUNTER: I'd say you should hurry to the port.\nThey have a furniture shop I've heard.",
            "KARL_HUNTER_9": "KARL: Thanks. And what might thy name be,\n good hunter?",
            "KARL_HUNTER_10": "HUNTER: 'Burp' at your service! :bows:",
            "KARL_HUNTER_11": "KARL: :tries to hide giggle:",
            "KARL_HUNTER_12": "HUNTER: Think my name's funny, do you?\n Begone, man with shiny head!",
            "PORTROAD_SIGN": "West to Port Knox.",
            "KARL_GUY_1": "KARL: Hi! I'm looking for a furniture shop.\nD'you know where I can find one?",
            "KARL_GUY_2": "GUY: You're standing beside it.\nI'm Erick the carpenter.",
            "KARL_GUY_3": "KARL: Hello Erick the carpenter,\nI'm Karl. I want to buy an armchair.",
            "KARL_GUY_4": "ERICK: Ah. That'll be 100,000 gold.",
            "KARL_GUY_5": "KARL: Haha, good one!",
            "KARL_GUY_6": "ERICK: I know.\nIt's still 100,000 gold.",
            "KARL_GUY_7": "KARL: Ok. You're kidding right?",
            "KARL_GUY_8": "ERICK: Nope. No-one can chop\ntrees anymore, so prices of furniture\nare high. Have you been living on some remote\n island or what?",
            "KARL_GUY_9": "KARL: Er... sort of. Where did everyone go?\nWhy are you the only guy here?",
            "KARL_GUY_10": "ERICK: All young men have been ordered\nby the King to work on the navy ships.\nThat's why the port is empty.",
            "KARL_GUY_11": "KARL: So what do I do now? :sob:",
            "KARL_GUY_12": "ERICK: Tell you what, the King's\nchief wizard has been trying to make wood.\nHe lives to the east of the crossroads.\nYou might want to meet him.",
            "KARL_GUY_13": "KARL: Argh. So much walking. My back hurts.\n Thanks though.\nI'll see the wizard.",
            "KARL_WIZ_1": "WIZARD: And who is this that dares enter\nmy domain?",
            "KARL_WIZ_2": "KARL: Greetings, your magicness. \nIt is I, Karl Drogo.\n",
            "KARL_WIZ_3": "WIZARD: Hello little Karl.\n I'm Hoodie Allen. What is it that you seek?",
            "KARL_WIZ_4": "KARL: Your magicness, I am on a great\nand noble quest-",
            "KARL_WIZ_5": "HOODIE: Ah! A Quest!\n I love quests! What is it?",
            "KARL_WIZ_6": "KARL: I, Karl, seek an armchair. For winter\nis coming, and I need to rock beside a fire.",
            "KARL_WIZ_7": "HOODIE: ...",
            "KARL_WIZ_8": "KARL: I have heard that you possess magic that\ncreates wood!",
            "KARL_WIZ_9": "HOODIE: Well, er...",
            "KARL_WIZ_10": "KARL: Hmm?",
            "KARL_WIZ_11": "HOODIE: The thing is, I am *trying* to produce wood.\nBut it doesn't work well.",
            "KARL_WIZ_12": "KARL: What do you mean, it doesn't work\nwell?", 
            "KARL_WIZ_13": "HOODIE: Well, this is how the magic works -\n1. I connect with my psychic powers to a world more\n advanced than ours. They call it 'Earth' - ",
            "KARL_WIZ_14": "KARL: 'They'?",
            "KARL_WIZ_15": "HOODIE: The inhabitants.\n2. I have magic that transports objects from that\nworld to this.",
            "KARL_WIZ_16": "HOODIE: But the problem is, they don't have wood.\nNo trees. Nothing.",
            "KARL_WIZ_17": "HOODIE: My magic works by pulling objects\nmade of the most abundant ogranic material\nabove the ground, into this world.",
            "KARL_WIZ_18": "HOODIE: Unfortunately, Since they have no trees\nanymore, the objects that come back are something else.\nThey call this material 'plastic'.",
            "KARL_WIZ_19": "HOODIE: This material is a waste in that world, and\nthey have great dumps of trash in that world.\nI don't know what to do with it.",
            "KARL_WIZ_20": "KARL: Oh... I must look elsewhere then.",
            "KARL_WIZ_21": "HOODIE: ...",
            "KARL_WIZ_22": "KARL: Wait. What is it like, this plastic?",
            "KARL_WIZ_23": "KARL: Well, for one, it's a LOT I have here and\nI can't burn it because it releases poison.",
            "KARL_WIZ_24": "HOODIE: Well, it depends. Some of it is thin and\n transparent, all plastic can be moulded when\nheat is applied, some of it is hard like wood - ",
            "KARL_WIZ_25": "KARL: Wait! You said that you have a lot\nof it! What if you mold the hard trash\nplastic by heating it and then\nmake an armchair out of it?",
            "KARL_WIZ_26": "HOODIE: !!!",
            "KARL_WIZ_27": "HOODIE: Of course I can! Why didn't I think of this!\nAnd the thin stuff can be used in palce of paper!",
            "KARL_WIZ_28": "KARL: Yay!",
            "KARL_WIZ_29": "HOODIE: I want to give a name to this process:\nRECYCLING!",
            "KARL_WIZ_30": "KARL: Let's do it!",
            "KARL_WIZ_31": "HOODIE: Alright. Hold on!",
            "KARL_WIZ_32": "HOODIE: There you go! The armchair's taking\nshape inside my castle. I'll deliver it\nto your house as a token of gratutude\n for your idea.",
            "KARL_WIZ_33": "KARL: Thanks! My quest is fulfilled!",
            "GAMEOVER": "Congratulations! The Game is over!\nThis was a technology demo of the RPG.js game toolkit.\n More features will be added to the toolkit soon\nand also to this game.\nStay tuned for the Great Recycling Adventure!"
    }
};
